# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f2d86c95657221539d10b4d61aae31b"
name = "test-shipping-free"
handle = "test-shipping-free"
application_url = "https://rated-blowing-washington-registry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sandboxseja.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rated-blowing-washington-registry.trycloudflare.com/auth/callback",
  "https://rated-blowing-washington-registry.trycloudflare.com/auth/shopify/callback",
  "https://rated-blowing-washington-registry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
